name: C/C++ CI

on: [push]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1
      with:
        submodule_update: ON
        run_tests: ON
        unit_test_build: -Dtest=ON
	create_package: ON
    - uses: actions/upload-artifact@v2
      with:
        path: _release/probstructs/libprobstructs.*
        name: artifact ${{ matrix.os }}
